CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE difficulty_level (
                                  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                  level_name VARCHAR(50) NOT NULL UNIQUE,
                                  level_value INTEGER NOT NULL
);

CREATE TABLE exercise (
                          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          exercise_name VARCHAR(255) NOT NULL,
                          muscle_division TEXT
);

CREATE TABLE role (
                      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      name VARCHAR(50) NOT NULL
);

CREATE TABLE "user" (
                        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        email VARCHAR(255) NOT NULL,
                        username VARCHAR(100) NOT NULL,
                        password_hash VARCHAR(100) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_role (
                           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           user_id BIGINT NOT NULL,
                           role_id BIGINT NOT NULL,
                           CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES "user" (id),
                           CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE workout_type (
                              id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                              type_name VARCHAR(100) NOT NULL
);

CREATE TABLE workout (
                         id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         user_id BIGINT,
                         workout_date TIMESTAMP,
                         difficulty_id BIGINT,
                         type_id BIGINT,
                         notes TEXT,
                         CONSTRAINT fk_workout_user FOREIGN KEY (user_id) REFERENCES "user" (id),
                         CONSTRAINT fk_workout_difficulty FOREIGN KEY (difficulty_id) REFERENCES difficulty_level (id),
                         CONSTRAINT fk_workout_type FOREIGN KEY (type_id) REFERENCES workout_type (id)
);

CREATE TABLE workout_exercise (
                                  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                  sets INTEGER,
                                  reps INTEGER,
                                  weight_kg DECIMAL(10,2),
                                  workout_id BIGINT,
                                  exercise_id BIGINT,
                                  CONSTRAINT fk_workout_exercise_workout FOREIGN KEY (workout_id) REFERENCES workout (id),
                                  CONSTRAINT fk_workout_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (id)
);

CREATE INDEX idx_user_role_user ON user_role (user_id);
CREATE INDEX idx_user_role_role ON user_role (role_id);
CREATE INDEX idx_workout_user ON workout (user_id);
CREATE INDEX idx_workout_difficulty ON workout (difficulty_id);
CREATE INDEX idx_workout_type ON workout (type_id);
CREATE INDEX idx_workout_exercise_workout ON workout_exercise (workout_id);
CREATE INDEX idx_workout_exercise_exercise ON workout_exercise (exercise_id);


INSERT INTO difficulty_level (level_name, level_value) VALUES
                                                           ('Начинающий', 1),
                                                           ('Легкий', 2),
                                                           ('Средний', 3),
                                                           ('Выше среднего', 4),
                                                           ('Продвинутый', 5),
                                                           ('Эксперт', 6),
                                                           ('Мастер', 7),
                                                           ('Профи', 8),
                                                           ('Чемпион', 9),
                                                           ('Элита', 10);


INSERT INTO exercise (exercise_name, muscle_division) VALUES
                                                          ('Приседания', 'Ноги, Ягодицы'),
                                                          ('Отжимания', 'Грудь, Трицепсы'),
                                                          ('Подтягивания', 'Спина, Бицепсы'),
                                                          ('Жим лежа', 'Грудь, Трицепсы'),
                                                          ('Становая тяга', 'Спина, Ноги'),
                                                          ('Планка', 'Пресс, Кор'),
                                                          ('Бег', 'Кардио, Ноги'),
                                                          ('Подъем гантелей', 'Плечи, Бицепсы'),
                                                          ('Скручивания', 'Пресс'),
                                                          ('Выпады', 'Ноги, Ягодицы');


INSERT INTO role (name) VALUES
                            ('Администратор'),
                            ('Тренер'),
                            ('Пользователь'),
                            ('Гость'),
                            ('Модератор'),
                            ('Премиум'),
                            ('Тестер'),
                            ('Блогер'),
                            ('Спортсмен'),
                            ('Куратор');


INSERT INTO "user" (email, username, password_hash, created_at) VALUES
                                                                    ('admin@example.com', 'Админ', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-01 10:00:00'),
                                                                    ('user1@example.com', 'Иван', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-02 11:00:00'),
                                                                    ('user2@example.com', 'Мария', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-03 12:00:00'),
                                                                    ('user3@example.com', 'Алексей', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-04 13:00:00'),
                                                                    ('user4@example.com', 'Елена', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-05 14:00:00'),
                                                                    ('user5@example.com', 'Дмитрий', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-06 15:00:00'),
                                                                    ('user6@example.com', 'Ольга', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-07 16:00:00'),
                                                                    ('user7@example.com', 'Сергей', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-08 17:00:00'),
                                                                    ('user8@example.com', 'Анна', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-09 18:00:00'),
                                                                    ('user9@example.com', 'Павел', '$2a$10$xJwL5v5Jz7t6VhD8bBZ8E.9Xz7t6VhD8bBZ8E', '2023-01-10 19:00:00');


INSERT INTO user_role (user_id, role_id) VALUES
                                             (1, 1),
                                             (2, 3),
                                             (3, 3),
                                             (4, 2),
                                             (5, 3),
                                             (6, 6),
                                             (7, 3),
                                             (8, 9),
                                             (9, 3),
                                             (10, 2);


INSERT INTO workout_type (type_name) VALUES
                                         ('Силовая'),
                                         ('Кардио'),
                                         ('Кроссфит'),
                                         ('Йога'),
                                         ('Пилатес'),
                                         ('Функциональная'),
                                         ('Стретчинг'),
                                         ('HIIT'),
                                         ('Круговая'),
                                         ('Бодибилдинг');


INSERT INTO workout (user_id, workout_date, difficulty_id, type_id, notes) VALUES
                                                                               (2, '2023-05-01 09:00:00', 3, 1, 'Первая тренировка'),
                                                                               (3, '2023-05-02 10:00:00', 2, 2, 'Утреннее кардио'),
                                                                               (4, '2023-05-03 11:00:00', 5, 3, 'Интенсивный кроссфит'),
                                                                               (5, '2023-05-04 12:00:00', 4, 4, 'Йога для расслабления'),
                                                                               (6, '2023-05-05 13:00:00', 6, 5, 'Пилатес - работа над кором'),
                                                                               (7, '2023-05-06 14:00:00', 3, 6, 'Функциональный тренинг'),
                                                                               (8, '2023-05-07 15:00:00', 7, 7, 'Растяжка после бега'),
                                                                               (9, '2023-05-08 16:00:00', 5, 8, 'HIIT - 20 минут'),
                                                                               (10, '2023-05-09 17:00:00', 4, 9, 'Круговая тренировка'),
                                                                               (2, '2023-05-10 18:00:00', 6, 10, 'Работа на массу');


INSERT INTO workout_exercise (sets, reps, weight_kg, workout_id, exercise_id) VALUES
                                                                                  (3, 10, 20.0, 1, 1), -- Приседания
                                                                                  (4, 12, 15.0, 1, 2), -- Отжимания
                                                                                  (3, 8, 30.0, 2, 3), -- Подтягивания
                                                                                  (5, 5, 50.0, 3, 4), -- Жим лежа
                                                                                  (4, 6, 70.0, 4, 5), -- Становая тяга
                                                                                  (3, 15, 10.0, 5, 6), -- Планка (вес не учитывается)
                                                                                  (1, 30, NULL, 6, 7), -- Бег (время в минутах)
                                                                                  (4, 10, 12.5, 7, 8), -- Подъем гантелей
                                                                                  (3, 20, NULL, 8, 9), -- Скручивания
                                                                                  (3, 12, 20.0, 9, 10), -- Выпады
                                                                                  (4, 8, 40.0, 10, 4), -- Жим лежа
                                                                                  (3, 10, 25.0, 10, 1); -- Приседания